### ISSUE TITLE
Textures not loading and always appear black

### ISSUE THREAD

**Issue by Wfel197** [lasa01/Plumber#176]
**Describe the bug**
When i import a hl2 map into blender with the file format .vmf the textures never load

**To Reproduce**
1. Import a 'd1_trainstation_01_d'
2. Go to viewport shading
3. See error

**Screenshots**
![image](https://github.com/lasa01/Plumber/assets/152092537/20c21702-bac5-438b-8e64-7145fced12fb)

**Details (please complete the following information):**
 - OS: Windows 11
 - Blender Version: 4.0
 - Addon Version: 1.0.0
 - Did you download a release or build the addon yourself: Downloaded

**Comment by chaixshot** [comment]
Back to 3.6 still work.

**Comment by lasa01** [comment]
Blender 4.0 is not supported currently, I'll try to fix this when I have time

**Comment by lasa01** [comment]
This is now fixed in the latest release

**Comment by Fennecai** [comment]
i am still getting this problem even after installing the new version from releases.
